sonar.projectKey=leonardodia3_proyectoInfra
sonar.organization=leonardodia3

sonar.projectName=proyectoInfra
sonar.projectVersion=1.0

sonar.sources=lambdas,local-deploy/backend,local-deploy/frontend,terraform,scripts
sonar.tests=lambdas,tests
sonar.test.inclusions=**/__tests__/**/*.js,tests/**/*.test.js
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**
sonar.javascript.lcov.reportPaths=lambdas/attendance/coverage/lcov.info,lambdas/attendanceHistory/coverage/lcov.info,lambdas/listStudents/coverage/lcov.info,lambdas/manualAttendance/coverage/lcov.info,lambdas/notifyAlert/coverage/lcov.info,lambdas/registerStudent/coverage/lcov.info
sonar.issue.ignore.multicriteria=terraformPublicRfidEndpoint
sonar.issue.ignore.multicriteria.terraformPublicRfidEndpoint.ruleKey=terraform:S6333
sonar.issue.ignore.multicriteria.terraformPublicRfidEndpoint.resourceKey=terraform/apigateway_attendance.tf

sonar.sourceEncoding=UTF-8
